# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Aysar
description: > # this means to ignore newlines until "baseurl:"
  Hi, I'm Aysar.  I like building things.  I occasionally use Ruby, JavaScript and Java.
  I occasionally finish and ship stuff.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://aysark.com" # the base hostname & protocol for your site
twitter_username: aysarkhalid
github_username:  aysark

# Build settings
markdown: kramdown
port: 3999
